### ISSUE TITLE
test failure in Scala 2.11 community build

### ISSUE THREAD

**Issue by SethTisue** [rssh/scala-gopher#11]
recently seen at e.g. https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/345/consoleFull:
```
[scala-gopher] [error] Failed tests:
[scala-gopher] [error] 	gopher.channels.SchedulerStartupTest
```

maybe the test should have a longer timeout or something?

**Comment by rssh** [comment]
Let's check: I increased timeout to 3 sec instead one:
https://github.com/rssh/scala-gopher/commit/259e90ac16e0df7df75d4510478487d980daab0c

The test itself check the basic functionality of akka scheduler, so only two reasons of failure are possible: timeout and problem in akka scheduling initialization.

**Comment by rssh** [comment]
Looks like issue is fixed in 347: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/347/console

**Comment by SethTisue** [comment]
thanks Ruslan!
