### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fommil** [rssh/scala-gopher#13]
Please add a license, preferably Apache 2.0, LGPLv3 or GPLv3.

**Comment by sirinath** [comment]
> Scala-gopher is open source (license is Apache2); binaries are available from the maven-central repository.

Please keep it ASL 2.0

**Comment by rssh** [comment]
Added copy of Apache-2.0  license to root project dir.

**Comment by fommil** [comment]
lol, you added a modified version of the Apache 2.0 LICENSE so even github can't recognise it. You're supposed to put your name and copyright information in a NOTICE file and leave the LICENSE file untouched.

**Comment by rssh** [comment]
thanks, fixed ;)
