### ISSUE TITLE
Extend to other constructs?

### ISSUE THREAD

**Issue by sirinath** [rssh/scala-gopher#15]
Is it possible to extend this to support:
- [ ] Petri net
- [ ] Kahn process networks
- [ ] Dataflow networks
- [ ] Flow based programming
- [ ] Functional reactive programming
- [ ] Incremental Spreadsheet like computing

**Comment by rssh** [comment]
All is possible, but to use something concrete it must be concrete ;)
[TODO: write text when ... will have free time  ]

**Comment by sirinath** [comment]
I think it is putting the same wine you got into different bottles. It is just the abstraction which changes and some properties and guarantees.
