### ISSUE TITLE
Do you need to Depend on Akka for this?

### ISSUE THREAD

**Issue by sirinath** [rssh/scala-gopher#16]
Do you need to rely on Akka for this. Perhaps you can have a simple underlying layer to implement the functionality you really use. Perhaps something like a mailbox processor. May be you can have your own lightweight actors also. Some issues with Akka is:

 - primitive specialization issues
 - large dependency
 - higher overhead
 - no control over memory and possible GC pauses once you enter the Akka API

**Comment by rssh** [comment]
TODO:  think about scope and motivation for akka-less version.  Now akka
