### ISSUE TITLE
FoldSelectSuite failing (intermittent?)

### ISSUE THREAD

**Issue by SethTisue** [rssh/scala-gopher#19]
seen in the Scala 2.12 community build at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1386/consoleFull:

```
[scala-gopher] [info] FoldSelectSuite:
[scala-gopher] [info] - fold-over-selector with changed read *** FAILED ***
[scala-gopher] [info]   java.util.concurrent.TimeoutException: Futures timed out after [2 seconds]
```

probably the timeout just needs to be increased...?

**Comment by rssh** [comment]
Increased, build https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1388/  is ok.
