### ISSUE TITLE
assorted failures in Scala community builds

### ISSUE THREAD

**Issue by SethTisue** [rssh/scala-gopher#20]
seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1389/consoleFull:

```
[scala-gopher] [info] AsyncSelectSuite:
[scala-gopher] [info] - async base: channel write, select read
[scala-gopher] [info] - async base: select write, select read
[scala-gopher] [info] - async base: select read, default action *** FAILED ***
[scala-gopher] [info]   consumer.isCompleted was false (AsyncSelectSuite.scala:106)
```

**Comment by rssh** [comment]
added extra consumer wait: https://github.com/rssh/scala-gopher/commit/f6b61fbc90176c079108057abb4db51e290b73d2
 // look for next build.

**Comment by SethTisue** [comment]
more failures:

```
[scala-gopher] [info] *** 2 TESTS FAILED ***
[scala-gopher] [error] Failed tests:
[scala-gopher] [error] 	gopher.channels.DuppedChannelsSuite
[scala-gopher] [error] 	gopher.channels.FoldSelectSuite
```

from https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/325/consoleFull

**Comment by SethTisue** [comment]
and another one:

```
[scala-gopher] [info] *** 1 TEST FAILED ***
[scala-gopher] [error] Failed tests:
[scala-gopher] [error] 	example.SieveSuite
```

from https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/326/consoleFull

**Comment by SethTisue** [comment]
This seems to be a systemic problem, so I'm going to disable scala-gopher's test suite (we'll compile the tests, but not run them); we could undo that change if you become confident you have a systemic fix (perhaps you could run the tests on a  slow and/or heavily loaded machine, to provoke similar failures)?

**Comment by SethTisue** [comment]
seen recently on 2.11 build:

```
[scala-gopher] [info] *** 6 TESTS FAILED ***
[scala-gopher] [error] Failed tests:
[scala-gopher] [error] 	gopher.channels.MacroSelectSuite
[scala-gopher] [error] 	gopher.transputers.TransputerRestartSuite
[scala-gopher] [error] 	gopher.channels.IOTimeoutsSuite
[scala-gopher] [error] 	gopher.transputers.ReplicateSuite
```

I'll disable running the tests in 2.11 as well (was already disabled for 2.12/2.13): https://github.com/scala/community-builds/pull/537

**Comment by SethTisue** [comment]
closing since it hasn't gotten any attention

**Comment by rssh** [comment]
btw, the problem is targeted in #21.  Another thing, as in any OSS project, that it's hard to say something concrete when it will be delivered ;)
